# Generated by Django 4.2 on 2025-04-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_userrecipe_day_calories_alter_userrecipe_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daycalories',
            options={'ordering': ['-date']},
        ),
    ]
