# Generated by Django 4.2 on 2025-04-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_alter_daycalories_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycategory',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_categories', to='planning.daycalories'),
        ),
    ]
