# Generated by Django 4.2 on 2025-03-27 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(max_length=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_lvl', models.CharField(choices=[('sedentary', 1.2), ('lightly_active', 1.375), ('moderately_active', 1.55), ('very_active', 1.725), ('extra_active', 1.9)], max_length=120)),
                ('year_of_birth', models.DateField()),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bmr', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('age', models.IntegerField(default=1, max_length=3)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
