# Generated by Django 4.2 on 2025-04-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCalories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('A', 'CALORIES FOCUS'), ('B', 'PROTEIN FOCUS'), ('C', 'CALORIES AND PROTEIN FOCUS')], max_length=1)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
